WITH TEMP AS (SELECT B."20SALESORG" AS SALESORG_KEY,
B."0SALESORG" AS SALES_ORG,
STRTOK(B."0CALDAY",'/',1) AS BILL_MONTH,
RIGHT(B."0CALDAY",4) AS BILL_YEAR,
CONCAT(STRTOK(B."0CALDAY",'/',1),'/',RIGHT(B."0CALDAY",4))AS BILL_DATE,
B."20CUSTOMER" AS CUSTOMER_KEY,
B."0CUSTOMER" AS CUSTOMER,
B."20MATERIAL" AS MATERIAL_KEY,
B."0MATERIAL" AS MATERIAL,
CONCAT(B."20SALESORG", B."20MATERIAL") AS SORG_MAT,
CONCAT(B."20SALESORG", B."20CUSTOMER") AS SORG_CUST,
CS."20CUST_GROUP" AS CUSTGROUP,
COUNT(B."0DOC_NUMBER") AS NUMSALESDOC,
SUM(B."GROSS($)") AS TOTAL_GROSS,
SUM(B."GROSSQTY") AS GROSS_QTY,
SUM(B."COST($)") AS TOTAL_COST,
--B."20DOC_CURRCY" AS CURRENCY_KEY
FROM TEST.TEMP.TEST_BILLING_CL_20240403 B
LEFT JOIN TEST.TEMP.TEST_CUS_SALES_CL_20240325 CS
ON CS."20SALESORG"=B."20SALESORG" AND CS."20CUSTOMER"=B."20CUSTOMER" AND CS."20DIVISION"=B."20DIVISION"
GROUP BY B."20SALESORG",--B."20DOC_CURRCY",
B."0SALESORG",STRTOK(B."0CALDAY",'/',1),RIGHT(B."0CALDAY",4),CS."20CUST_GROUP",B."20CUSTOMER",B."0CUSTOMER",B."20MATERIAL",B."0MATERIAL"
HAVING SUM(B."GROSS($)")>0
ORDER BY B."20SALESORG"),

K01 AS (
SELECT T.*, 
C."20COUNTRY" AS Address_Country
FROM TEMP T
LEFT JOIN TEST.TEMP.TEST1_CUSTOMER_CL_20240405 C
ON T.CUSTOMER_KEY=C."20CUSTOMER"
)
SELECT *
FROM K01